# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    groups:
        # Filter name
        label: adil.smartjob::lang.job.department
        # Model Class name
        modelClass: Adil\Smartjob\Models\Department
        # Model attribute to display for the name
        nameFrom: department_name
        # SQL conditions
        conditions: department_id in (:filtered)
        # Filter scope function
        # scope: filterByGroup

    created_date:
        label: adil.smartjob::lang.job.created_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    activated:
        # Filter name
        label: adil.smartjob::lang.job.is_expired
        # Filter type
        type: switch
        # SQL conditions
        conditions:
            - is_expired = '0' # Expired
            - is_expired = '1' # Active
    positionfilled:
        # Filter name
        label: adil.smartjob::lang.job.is_filled
        # Filter type
        type: switch
        # SQL conditions
        conditions:
            - is_filled = '0'
            - is_filled = '1'